name: Release new version

on:
  workflow_dispatch:
    inputs:
      version_name:
        description: 'Version name'
        required: true
      pypi_repo:
        description: 'PyPI repository'
        required: true
        type: choice
        default: 'pypi'
        options:
          - 'pypi'
          - 'testpypi'
  release:
    types: [published]

jobs:
  release:
    name: Release ${{ github.event.release.tag_name || inputs.version_name }}
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          cache: pip

      - name: Build
        env:
          SETUPTOOLS_SCM_PRETEND_VERSION: ${{ inputs.version_name }}
        run: |
          echo Got env version: $SETUPTOOLS_SCM_PRETEND_VERSION
          python -m pip install --upgrade pip
          pip install build
          python -m build

      - name: Store build artifact
        uses: actions/upload-artifact@v4
        with:
          path: dist

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
        if: ${{ inputs.pypi_repo == 'testpypi' }}

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: ${{ inputs.pypi_repo == 'pypi' || github.event_name == 'release' }}
